### ISSUE TITLE
Get IP results without FTP

### ISSUE THREAD

**Issue by johnymas** [ericsizemore/simple_counter#4]
Hi, Eric Firstly thank you for your contribution. Is there any other way to get IP results without FTP such as admin access or similar? Thank you.

**Comment by mchaos** [comment]
You could just do an include on the blank index.html that calls the 2 txt files with the logs. or some other page. Then all you have to do is call that page and it will show the txt file contents. Or you can change the setting to write to counter.html and ips.html, and then call those pages specifically and they will load in the browser.

it would be real easy to make a pretty page to show off the contents of those 2 files.

**Comment by ericsizemore** [comment]
It is something I intend to add, though I'm considering the best course. Sure, I could simply make them html pages or have a file that reads and outputs the information; however, I want a more secure solution, as I wouldn't want IP information publicly available :)

Just trying to determine the easiest way for users to setup/access it, without too much involved.

**Comment by ericsizemore** [comment]
As part of #13 - I've implemented this in a round about way in https://github.com/ericsizemore/simple_counter/tree/6.x-dev

There will be a function that fetches ip information called `fetchCurrentIpList()`. I feel this may be the better approach than what I was originally considering. This allows users of the library to retrieve and display this information any way they see fit, rather than me authentication/etc. into the library.

I am curious what y'all think about this approach, so leaving the issue open for now as development for 6.0 is still ongoing, and in its early stages.

**Comment by ericsizemore** [comment]
As of the new 6.0.0 release, this is possible for anyone to implement themselves.

https://github.com/ericsizemore/simple_counter/blob/v6.0.0/docs/flatfile-storage.md#fetchcurrentiplist
